name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Testing test
      id: testing-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Testing test
        setup-command: ''
        command: python autograder.py
        timeout: 1
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTING-TEST_RESULTS: "${{steps.testing-test.outputs.result}}"
      with:
        runners: testing-test
